### ISSUE TITLE
Crash on client load

### ISSUE THREAD

**Issue by daniorio** [FalsePattern/GasStation#11]
I try load GasStation on my client, but it is crashed. Log here. GasStation latest release.
[fml-client-3.log](https://github.com/FalsePattern/GasStation/files/10145555/fml-client-3.log)

**Comment by FalsePattern** [comment]
GasStation is not compatible with your launcher, it seems like that launcher breaks code used by mixins (gasstation's backend) to inject code. Please try a different launcher.
