### ISSUE TITLE
Crash when using both GasStation and littleMaidMobX

### ISSUE THREAD

**Issue by SugarSteak** [FalsePattern/GasStation#19]
Minecraft launches successfully with either of those mods, but not with both.
[fml-client-latest.log](https://github.com/FalsePattern/GasStation/files/10714732/fml-client-latest.log)

**Comment by SugarSteak** [comment]
Sorry, closed by mistake.

**Comment by makamys** [comment]
This is an issue on LittleMaidMobX's side. They attempt to *load every class in every mod jar* when searching for models. In fact, this issue happens with any mod that embeds Mixin, e.g. https://github.com/makamys/MAtmos/issues/12.

There is an enhanced fork that does not have this issue, I recommend using it instead: https://github.com/Goujer/LittleMaidMobEnhanced

**Comment by SugarSteak** [comment]
Thank you, that one has been working fine so far.
