### ISSUE TITLE
FalsePattern and GTNH Series of dependent mods now incompatible

### ISSUE THREAD

**Issue by MysteriousSheep** [FalsePattern/GasStation#6]
The newer [GTNH](https://github.com/GTNewHorizons) dependent mods are now requiring [GTNHMixins](https://github.com/GTNewHorizons/GTNHMixins) which will not load with [GasStation](https://github.com/FalsePattern/GasStation)

The newer [FalsePattern](https://github.com/FalsePattern) dependent mods are now requiring [GasStation](https://github.com/FalsePattern/GasStation) which will not load with [GTNHMixins](https://github.com/GTNewHorizons/GTNHMixins)

Unfortunately, neither series of mods work with just one or the other.

Both files conflict as being a duplicate mod "spongemixins"

![image](https://user-images.githubusercontent.com/115964468/196079595-1e0f8da1-c243-42ff-b37f-9e0fb0af5c7d.png)

https://github.com/GTNewHorizons/GTNHMixins/issues/1

**Comment by tyrael93** [comment]
As you said, they're incompatible. Code-wise, it's a nightmare on the GTNH mixins side because everything got changed around. 
On top of that, FP is not particularly interested in adding NH compat.
Basically, that's not going to be fixed.
