### ISSUE TITLE
Plugin Interaction Issue || Crucible (Thermos)

### ISSUE THREAD

**Issue by KAMKEEL** [FalsePattern/GasStation#7]
**GasStation** tries to interact with the Gringotts plugin causing the plugin to crash and disable on startup.

Jar -> Crucible: 5.3

Mods:
- GasStation (3.5)

Plugins
- Gringotts (https://dev.bukkit.org/projects/gringotts/files/921446) v2.3 to v2.9
- Vault (https://dev.bukkit.org/projects/vault/files/792396) v1.4.1 

IN ORDER TO RUN **CRUCIBLE** for this PLUGIN:

ADD THIS FILE ([java.policy](https://github.com/FalsePattern/GasStation/files/9891928/JavaPolicy.zip)) TO DIRECTORY where **CRUCIBLE.JAR** is located and add
`-Djava.security.policy=./java.policy` to arguments before the `-jar` in startup parameters

**Comment by FalsePattern** [comment]
You can make the plugin work by renaming crucible.jar to minecraft.jar
